# 印刷PDF用設定ファイル
# 元々の設定ファイルから項目を継承する
inherit: ["config.yml"]

# 表紙と裏表紙は作らないが、そのかわりに大扉を入れる
cover: title.xhtml

# 縦書き
direction: "rtl"

# 大扉としては入れない
titlepage: false

# 奥付は自作したXMTMLファイルを使う
colophon: colophon.xhtml

# 著者紹介は自作したXMTMLファイルを使う
# profile: profile.xhtml
# profiletitle: 著者紹介

# 目次の章立ての部分にリンクを作らない
chapterlink: null

# 外部リンクを無効にする
externallink: false